---
- hosts: hypercat
  remote_user: ideam
  tasks:
  - include: tasks/hypercat/start_hypercat.yaml

- hosts: rabbitmq
  remote_user: ideam
  vars_files:
    - host_vars/rabbitmq
  tasks:
  - include: tasks/rabbitmq/start_rabbitmq.yaml

- hosts: tomcat
  remote_user: ideam
  tasks:
  - include: tasks/tomcat/start_tomcat.yaml

- hosts: ldapd
  remote_user: ideam
  tasks:
  - include: tasks/ldapd/start_ldapd.yml

- hosts: kong
  remote_user: ideam
  tasks:
  - include: tasks/kong/start_kong.yml

- hosts: apt_repo
  remote_user: ideam
  tasks:
  - include: tasks/apt_repo/start_apt_repo.yml

- hosts: pushpin
  remote_user: root
  tasks:
  - include: tasks/pushpin/start_pushpin.yml

- hosts: elasticsearch
  remote_user: ideam
  tasks:
  - include: tasks/elasticsearch/start_elasticsearch.yml

- hosts: kong
  remote_user: ideam
  tasks:
  - name: Create database entity
    uri:
      url: http://localhost:8000/api/1.0.0/register
      method: POST
      status_code: [200,409]
      headers:
        Content-Type: "application/json"
        apikey: "guest"
      body: "{{ lookup('file','config/database_register.json') }}"
      body_format: json
      validate_certs: no

- hosts: videoserver
  remote_user: root
  tasks:

  - name: Start php service
    service: name=php7.0-fpm state=restarted

  - name: Stop backend
    command: sh stop.sh
    args:
      chdir: /home/ideam/video-stream-server/backend/
    ignore_errors: True

  - name: Stop frontend
    command: sh stop.sh
    args:
      chdir: /home/ideam/video-stream-server/frontend
    ignore_errors: True

  - name: Start backend
    command: sh start.sh
    args:
      chdir: /home/ideam/video-stream-server/backend/

  - name: Start frontend
    command: sh start.sh
    args:
      chdir: /home/ideam/video-stream-server/frontend

