FROM ubuntu:16.04
MAINTAINER Harish Anand "https://github.com/harishanand95"

RUN apt-get update

RUN apt-get install -y openssh-server sudo
RUN mkdir /var/run/sshd

RUN echo 'root:rbccps@123456' |chpasswd

RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN mkdir ~/.ssh
RUN apt-get install -y python
EXPOSE 22
CMD    ["/usr/sbin/sshd", "-D"]
