FROM harishanand95/middleware-apt-packages:0.1
MAINTAINER Harish Anand "https://github.com/harishanand95"

RUN apt-get update
RUN apt-get install -y openssh-server sudo

RUN rm /etc/ssh/ca-user-certificate-key.pub
COPY config/certificate_authority/keys/ca-user-certificate-key.pub /etc/ssh/ca-user-certificate-key.pub
EXPOSE 22
EXPOSE 8000
CMD    ["/usr/sbin/sshd", "-D"]
